steps:
  # Build ce-deployer docker image
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/ce-deployer:${_IMAGE_TAG}
      - --destination=gcr.io/climate-engine-public/climate-engine/ce-deployer:${_IMAGE_TAG}
      - --cache=true
      - --cache-ttl=48h
      - --dockerfile=Dockerfile-ce-deployer

  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/deployer:${_IMAGE_TAG}
      - --destination=gcr.io/climate-engine-public/climate-engine/deployer:${_IMAGE_TAG}
      - --cache=true
      - --cache-ttl=48h
      - --dockerfile=Dockerfile-mp-deployer

substitutions:
    _IMAGE_TAG: ${TAG_NAME#v}