steps:
  # Access the id_github file from Secret Manager, and setup SSH
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      cp known_hosts.github /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  # Get submodules
  - name: 'gcr.io/cloud-builders/git'
    args: [ 'submodule', 'update', '--init', '--recursive' ]
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # Build ce-deployer docker image
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/ce-deployer:latest
      - --destination=gcr.io/climate-engine-public/climate-engine/ce-deployer:latest
      - --cache=true
      - --cache-ttl=48h
      - --dockerfile=Dockerfile-ce-deployer

  # Marketplace Deployer (calls a Job to run CE Deployer)
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/deployer:latest
      - --destination=gcr.io/climate-engine-public/climate-engine/deployer:latest
      - --cache=true
      - --cache-ttl=48h
      - --dockerfile=Dockerfile

availableSecrets:
  secretManager:
  - versionName: projects/378574554703/secrets/cloudbuild-github-key/versions/latest
    env: 'SSH_KEY'