x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '1.0.2'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  images:
    ce-deployer:
      properties:
        ce_deployer_image:
          type: FULL
    ubbagent:
      properties:
        image_ubbagent:
          type: FULL
          # default: gcr.io/cloud-marketplace-tools/metering/ubbagent:latest

  clusterConstraints:
    assistedClusterCreation:
      type: DISABLED
      creationGuidance: "Create a minimal cluster with a Kubernetes secret containing the Service Account json."

properties:
  app_name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  sql_password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 10
        includeSymbols: False
        base64: False
  sa_secret_name:
    type: string
    title: "Kubernetes secret containing SA json"
    default: "google-cloud-key"
  reportingSecret:
    type: string
    default: "notasecret"
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - app_name
  - namespace
  - sql_password
  - sa_secret_name
  - reportingSecret
