x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '1.0.4'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  images:
    ce-deployer:
      properties:
        ce_deployer_image:
          type: FULL

  clusterConstraints:
    assistedClusterCreation:
      type: DISABLED
      creationGuidance: >-
        The install cluster must:
          - Be GKE Standard (not Autopilot)
          - Have at least one node with machine type "e2-medium"
          - Contain a Kubernetes Secret containing the JSON key of a Service Account with Owner permissions
        For more detailed information see: https://github.com/climateengine/ce-marketplace-deployer#readme

properties:
  app_name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  sql_password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 10
        includeSymbols: False
        base64: False
  sa_secret_name:
    type: string
    title: "Kubernetes secret containing SA json"
    default: "google-cloud-key"
  reportingSecret:
    type: string
    default: "fake-reporting-secret"
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - app_name
  - namespace
  - sql_password
  - sa_secret_name
  - reportingSecret
