x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '1.0.1'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  images:
    ce-deployer:
      properties:
        ce_deployer_image:
          type: FULL

properties:
  app_name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  sql_password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 10
        includeSymbols: False
        base64: False
  sa_secret_name:
    type: string

required:
  - app_name
  - namespace
  - sql_password
  - sa_secret_name
