apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ce-engine-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ce-engine-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ce-engine-api.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: ubbagent-config
          configMap:
            name: {{ .Chart.Name }}-ubbagent-config
      containers:
        - name: ubbagent
          image: {{ .Values.image }}
          env:
          - name: AGENT_CONFIG_FILE
            value: "/etc/ubbagent/config.yaml"
          - name: AGENT_LOCAL_PORT
            value: "4567"
          - name: AGENT_ENCODED_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.reporting_secret }}
                key: reporting-key
          - name: AGENT_CONSUMER_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.reporting_secret }}
                key: consumer-id
          volumeMounts:
          - name: ubbagent-config
            mountPath: /etc/ubbagent